/*BORRA DE LA BASE DE DATOS
DROP DATABASE RD;
*/

/*CREACION DE LA BASE DE DATOS*/
CREATE DATABASE RD;

/*USO DE LA BASE DE DATOS*/
USE RD;

/*CREACION DE LA TABLA REGIONES*/
CREATE TABLE Regiones(
Id INT AUTO_INCREMENT PRIMARY KEY ,
Descripcion VARCHAR(100) NOT NULL UNIQUE CHECK (Descripcion NOT LIKE ''),
Estado BOOLEAN DEFAULT 1 CHECK ( Estado IN (0,1))
);

/*CREACION DE LA TABLA PROVINCIAS*/
CREATE TABLE Provincias(
Id INT AUTO_INCREMENT PRIMARY KEY,
IdRegion INT NOT NULL,
FOREIGN KEY (IdRegion) REFERENCES Regiones(Id),
Descripcion VARCHAR(100) NOT NULL UNIQUE CHECK (Descripcion NOT LIKE ''),
Estado BOOLEAN DEFAULT 1 CHECK ( Estado IN (0,1))
);

/*CREACION DE LA TABLA MUNICIPIOS*/
CREATE TABLE Municipios(
Id INT AUTO_INCREMENT PRIMARY KEY,
IdProvincia INT NOT NULL,
FOREIGN KEY (IdProvincia) REFERENCES Provincias(Id),
Descripcion VARCHAR(100) NOT NULL UNIQUE CHECK (Descripcion NOT LIKE ''),
Estado BOOLEAN DEFAULT 1 CHECK ( Estado IN (0,1))
);

/*CREACION DE LA TABLA Distritos_Municipales*/
CREATE TABLE Distritos_Municipales(
Id INT AUTO_INCREMENT PRIMARY KEY,
IdMunicipio INT NOT NULL,
FOREIGN KEY (IdMunicipio) REFERENCES Municipios(Id),
Descripcion VARCHAR(100) NOT NULL CHECK (Descripcion NOT LIKE ''),
Estado BOOLEAN DEFAULT 1 CHECK ( Estado IN (0,1))
);

/*CREACION DE LA TABLA EMPLEADOS*/
CREATE TABLE Empleados(
Id INT AUTO_INCREMENT PRIMARY KEY,
Nombre VARCHAR(40) NOT NULL CHECK (Nombre NOT LIKE ''),
Apellido VARCHAR(40) NOT NULL CHECK (Apellido NOT LIKE ''),
Cedula CHAR(11) NOT NULL UNIQUE CHECK (Cedula NOT LIKE '%[^0-9]%' AND LENGTH(Cedula) = 11),
Fecha_Nacimiento DATE NOT NULL,
Genero CHAR(1) NOT NULL CHECK (Genero IN ('M','F')),
IdRegion INT NOT NULL,
FOREIGN KEY (IdRegion) REFERENCES Regiones(Id),
IdProvincia INT NOT NULL,
FOREIGN KEY (IdProvincia) REFERENCES Provincias(Id),
IdMunicipio INT NOT NULL,
FOREIGN KEY (IdMunicipio) REFERENCES Municipios(Id),
IdDistritoMunicipal INT NOT NULL,
FOREIGN KEY (IdDistritoMunicipal) REFERENCES Distritos_Municipales(Id),
IdEmpleadoSupervisor INT,
FOREIGN KEY (IdEmpleadoSupervisor) REFERENCES Empleados(Id),
Estado BOOLEAN DEFAULT 1 CHECK ( Estado IN (0,1))
);

/*CREACION DE LA TABLA TIPO TELEFONOS*/
CREATE TABLE Tipo_Telefonos(
Id INT AUTO_INCREMENT PRIMARY KEY,
TipoTelefono VARCHAR(10) NOT NULL,
Estado BOOLEAN DEFAULT 1 CHECK (Estado IN (0,1))
);

/*CREACION DE LA TABLA TELEFONOS*/
CREATE TABLE Telefonos(
Id INT AUTO_INCREMENT PRIMARY KEY,
IdEmpleado INT NOT NULL,
FOREIGN KEY (IdEmpleado) REFERENCES Empleados(Id),
Telefono CHAR(10) NOT NULL CHECK (Telefono RLIKE '[8][024][9][0-9]{7}'),
IdTipoTelefono INT NOT NULL,
FOREIGN KEY (IdTipoTelefono) REFERENCES Tipo_Telefonos(Id),
Estado BOOLEAN DEFAULT 1 CHECK ( Estado IN (0,1))
);

/*INSERCION DE LOS DATOS EN LA TABLA REGIONES TODOS EN UN SOLO QUERY*/
INSERT INTO Regiones (Descripcion) VALUES ('NORTE O CIBAO'),('ESTE'),('SUR');

/*INSERCION DE LOS DATOS DE LA REGION NORTE EN LA TABLA PROVINCIAS TODOS EN UN SOLO QUERY*/
INSERT INTO Provincias (IdRegion,Descripcion) VALUES 
(1,'DAJABÓN'),
(1,'DUARTE'),
(1,'ESPAILLAT'),
(1,'HERMANAS MIRABAL'),
(1,'LA VEGA'),
(1,'MARÍA TRINIDAD SÁNCHEZ'),
(1,'MONSEÑOR NOUEL'),
(1,'MONTE CRISTI'),
(1,'PUERTO PLATA'),
(1,'SAMANÁ'),
(1,'SÁNCHEZ RAMÍREZ'),
(1,'SANTIAGO'),
(1,'SANTIAGO RODRÍGUEZ'),
(1,'VALVERDE');

/*INSERCION DE LOS DATOS DE LA PROVINCIA DAJABÓN EN LA TABLA MUNICIPIOS TODOS EN UN SOLO QUERY*/
INSERT INTO Municipios (IdProvincia,Descripcion) VALUES 
(1,'DAJABÓN'),
(1,'EL PINO'),
(1,'LOMA DE CABRERA'),
(1,'PARTIDO'),
(1,'RESTAURACIÓN');

/*INSERCION DE LOS DATOS DE LA PROVINCIA DUARTE EN LA TABLA MUNICIPIOS TODOS EN UN SOLO QUERY*/
INSERT INTO Municipios (IdProvincia,Descripcion) VALUES 
(2,'ARENOSO'),
(2,'CASTILLO'),
(2,'EUGENIO MARÍA DE HOSTOS'),
(2,'LAS GUÁRANAS'),
(2,'PIMENTEL'),
(2,'SAN FRANCISCO DE MACORÍS'),
(2,'VILLA RIVA');

/*INSERCION DE LOS DATOS DE LA PROVINCIA ESPAILLAT EN LA TABLA MUNICIPIOS TODOS EN UN SOLO QUERY*/
INSERT INTO Municipios (IdProvincia,Descripcion) VALUES 
(3,'CAYETANO GERMOSÉN'),
(3,'GASPAR HERNÁNDEZ'),
(3,'JAMAO AL NORTE'),
(3,'MOCA');

/*INSERCION DE LOS DATOS DE LA PROVINCIA HERMANAS MIRABAL EN LA TABLA MUNICIPIOS TODOS EN UN SOLO QUERY*/
INSERT INTO Municipios (IdProvincia,Descripcion) VALUES 
(4,'SALCEDO'),
(4,'TENARES'),
(4,'VILLA TAPIA');

/*INSERCION DE LOS DATOS DE LA PROVINCIA LA VEGA EN LA TABLA MUNICIPIOS TODOS EN UN SOLO QUERY*/
INSERT INTO Municipios (IdProvincia,Descripcion) VALUES 
(5,'CONSTANZA'),
(5,'JARABACOA'),
(5,'JIMA ABAJO'),
(5,'LA CONCEPCIÓN DE LA VEGA');

/*INSERCION DE LOS DATOS DE LA PROVINCIA MARÍA TRINIDAD SÁNCHEZ EN LA TABLA MUNICIPIOS TODOS EN UN SOLO QUERY*/
INSERT INTO Municipios (IdProvincia,Descripcion) VALUES 
(6,'CABRERA'),
(6,'EL FACTOR'),
(6,'NAGUA'),
(6,'RÍO SAN JUAN');

/*INSERCION DE LOS DATOS DE LA PROVINCIA MONSEÑOR NOUEL EN LA TABLA MUNICIPIOS TODOS EN UN SOLO QUERY*/
INSERT INTO Municipios (IdProvincia,Descripcion) VALUES 
(7,'BONAO'),
(7,'MAIMÓN'),
(7,'PIEDRA BLANCA');

/*INSERCION DE LOS DATOS DE LA PROVINCIA MONTE CRISTI EN LA TABLA MUNICIPIOS TODOS EN UN SOLO QUERY*/
INSERT INTO Municipios (IdProvincia,Descripcion) VALUES 
(8,'CASTAÑUELAS'),
(8,'GUAYUBÍN'),
(8,'LAS MATAS DE SANTA CRUZ'),
(8,'MONTE CRISTI'),
(8,'PEPILLO SALCEDO'),
(8,'VILLA VÁSQUEZ');

/*INSERCION DE LOS DATOS DE LA PROVINCIA PUERTO PLATA EN LA TABLA MUNICIPIOS TODOS EN UN SOLO QUERY*/
INSERT INTO Municipios (IdProvincia,Descripcion) VALUES 
(9,'ALTAMIRA'),
(9,'GUANANICO'),
(9,'IMBERT'),
(9,'LOS HIDALGOS'),
(9,'LUPERÓN'),
(9,'PUERTO PLATA'),
(9,'SOSÚA'),
(9,'VILLA ISABELA'),
(9,'VILLA MONTELLANO');

/*INSERCION DE LOS DATOS DE LA PROVINCIA SAMANÁ EN LA TABLA MUNICIPIOS TODOS EN UN SOLO QUERY*/
INSERT INTO Municipios (IdProvincia,Descripcion) VALUES 
(10,'LAS TERRENAS'),
(10,'SAMANÁ'),
(10,'SÁNCHEZ');

/*INSERCION DE LOS DATOS DE LA PROVINCIA SÁNCHEZ RAMÍREZ EN LA TABLA MUNICIPIOS TODOS EN UN SOLO QUERY*/
INSERT INTO Municipios (IdProvincia,Descripcion) VALUES 
(11,'CEVICOS'),
(11,'COTUÍ'),
(11,'FANTINO'),
(11,'LA MATA');

/*INSERCION DE LOS DATOS DE LA PROVINCIA SANTIAGO EN LA TABLA MUNICIPIOS TODOS EN UN SOLO QUERY*/
INSERT INTO Municipios (IdProvincia,Descripcion) VALUES 
(12,'BISONÓ'),
(12,'JÁNICO'),
(12,'LICEY AL MEDIO'),
(12,'PUÑAL'),
(12,'SABANA IGLESIA'),
(12,'SAN JOSÉ DE LAS MATAS'),
(12,'SANTIAGO'),
(12,'TAMBORIL'),
(12,'VILLA GONZÁLEZ');

/*INSERCION DE LOS DATOS DE LA PROVINCIA SANTIAGO RODRÍGUEZ EN LA TABLA MUNICIPIOS TODOS EN UN SOLO QUERY*/
INSERT INTO Municipios (IdProvincia,Descripcion) VALUES 
(13,'MONCIÓN'),
(13,'SAN IGNACIO DE SABANETA'),
(13,'VILLA LOS ALMÁCIGOS');

/*INSERCION DE LOS DATOS DE LA PROVINCIA VALVERDE EN LA TABLA MUNICIPIOS TODOS EN UN SOLO QUERY*/
INSERT INTO Municipios (IdProvincia,Descripcion) VALUES 
(14,'ESPERANZA'),
(14,'LAGUNA SALADA'),
(14,'MAO');

/*INSERCION DE LOS DATOS DE LA REGION ESTE EN LA TABLA PROVINCIAS TODOS EN UN SOLO QUERY*/
INSERT INTO Provincias (IdRegion,Descripcion) VALUES 
(2,'DISTRITO NACIONAL'),
(2,'EL SEIBO'),
(2,'HATO MAYOR'),
(2,'LA ALTAGRACIA'),
(2,'LA ROMANA'),
(2,'MONTE PLATA'),
(2,'SAN PEDRO DE MACORÍS'),
(2,'SANTO DOMINGO');


/*INSERCION DEL DISTRITO NACIONAL EN LA TABLA MUNICIPIOS TODOS EN UN SOLO QUERY*/
INSERT INTO Municipios (IdProvincia,Descripcion) VALUES 
(15,'SANTO DOMINGO');

/*INSERCION DE LOS DATOS DE LA PROVINCIA EL SEIBO EN LA TABLA MUNICIPIOS TODOS EN UN SOLO QUERY*/
INSERT INTO Municipios (IdProvincia,Descripcion) VALUES 
(16,'EL SEIBO'),
(16,'MICHES');

/*INSERCION DE LOS DATOS DE LA PROVINCIA HATO MAYOR EN LA TABLA MUNICIPIOS TODOS EN UN SOLO QUERY*/
INSERT INTO Municipios (IdProvincia,Descripcion) VALUES 
(17,'EL VALLE'),
(17,'HATO MAYOR DEL REY'),
(17,'SABANA DE LA MAR');

/*INSERCION DE LOS DATOS DE LA PROVINCIA LA ALTAGRACIA EN LA TABLA MUNICIPIOS TODOS EN UN SOLO QUERY*/
INSERT INTO Municipios (IdProvincia,Descripcion) VALUES 
(18,'HIGÜEY'),
(18,'SAN RAFAEL DEL YUMA');

/*INSERCION DE LOS DATOS DE LA PROVINCIA LA ROMANA EN LA TABLA MUNICIPIOS TODOS EN UN SOLO QUERY*/
INSERT INTO Municipios (IdProvincia,Descripcion) VALUES 
(19,'GUAYMATE'),
(19,'LA ROMANA'),
(19,'VILLA HERMOSA');

/*INSERCION DE LOS DATOS DE LA PROVINCIA MONTE PLATA EN LA TABLA MUNICIPIOS TODOS EN UN SOLO QUERY*/
INSERT INTO Municipios (IdProvincia,Descripcion) VALUES 
(20,'BAYAGUANA'),
(20,'MONTE PLATA'),
(20,'PERALVILLO'),
(20,'SABANA GRANDE DE BOYÁ'),
(20,'YAMASÁ');

/*INSERCION DE LOS DATOS DE LA PROVINCIA SAN PEDRO DE MACORÍS EN LA TABLA MUNICIPIOS TODOS EN UN SOLO QUERY*/
INSERT INTO Municipios (IdProvincia,Descripcion) VALUES 
(21,'CONSUELO'),
(21,'GUAYACANES'),
(21,'QUISQUEYA'),
(21,'RAMÓN SANTANA'),
(21,'SAN JOSÉ DE LOS LLANOS'),
(21,'SAN PEDRO DE MACORÍS');

/*INSERCION DE LOS DATOS DE LA PROVINCIA SANTO DOMINGO EN LA TABLA MUNICIPIOS TODOS EN UN SOLO QUERY*/
INSERT INTO Municipios (IdProvincia,Descripcion) VALUES 
(22,'BOCA CHICA'),
(22,'LOS ALCARRIZOS'),
(22,'PEDRO BRAND'),
(22,'SAN ANTONIO DE GUERRA'),
(22,'SANTO DOMINGO ESTE'),
(22,'SANTO DOMINGO NORTE'),
(22,'SANTO DOMINGO OESTE');

/*INSERCION DE LOS DATOS DE LA REGION SUR EN LA TABLA PROVINCIAS TODOS EN UN SOLO QUERY*/
INSERT INTO Provincias (IdRegion,Descripcion) VALUES 
(3,'AZUA'),
(3,'BAHORUCO'),
(3,'BARAHONA'),
(3,'ELÍAS PIÑA'),
(3,'INDEPENDENCIA'),
(3,'PEDERNALES'),
(3,'PERAVIA'),
(3,'SAN CRISTÓBAL'),
(3,'SAN JOSÉ DE OCOA'),
(3,'SAN JUAN');

/*INSERCION DE LOS DATOS DE LA PROVINCIA AZUA EN LA TABLA MUNICIPIOS TODOS EN UN SOLO QUERY*/
INSERT INTO Municipios (IdProvincia,Descripcion) VALUES 
(23,'AZUA DE COMPOSTELA'),
(23,'ESTEBANÍA'),
(23,'GUAYABAL'),
(23,'LAS CHARCAS'),
(23,'LAS YAYAS DE VIAJAMA'),
(23,'PADRE LAS CASAS'),
(23,'PERALTA'),
(23,'PUEBLO VIEJO'),
(23,'SABANA YEGUA'),
(23,'TÁBARA ARRIBA');

/*INSERCION DE LOS DATOS DE LA PROVINCIA BAHORUCO EN LA TABLA MUNICIPIOS TODOS EN UN SOLO QUERY*/
INSERT INTO Municipios (IdProvincia,Descripcion) VALUES 
(24,'GALVÁN'),
(24,'LOS RÍOS'),
(24,'NEIBA'),
(24,'TAMAYO'),
(24,'VILLA JARAGUA');

/*INSERCION DE LOS DATOS DE LA PROVINCIA BARAHONA EN LA TABLA MUNICIPIOS TODOS EN UN SOLO QUERY*/
INSERT INTO Municipios (IdProvincia,Descripcion) VALUES 
(25,'BARAHONA'),
(25,'CABRAL'),
(25,'EL PEÑÓN'),
(25,'ENRIQUILLO'),
(25,'FUNDACIÓN'),
(25,'JAQUIMEYES'),
(25,'LA CIÉNAGA'),
(25,'LAS SALINAS'),
(25,'PARAÍSO'),
(25,'POLO'),
(25,'VICENTE NOBLE');

/*INSERCION DE LOS DATOS DE LA PROVINCIA ELÍAS PIÑA EN LA TABLA MUNICIPIOS TODOS EN UN SOLO QUERY*/
INSERT INTO Municipios (IdProvincia,Descripcion) VALUES 
(26,'BÁNICA'),
(26,'COMENDADOR'),
(26,'EL LLANO'),
(26,'HONDO VALLE'),
(26,'JUAN SANTIAGO'),
(26,'PEDRO SANTANA');

/*INSERCION DE LOS DATOS DE LA PROVINCIA INDEPENDENCIA EN LA TABLA MUNICIPIOS TODOS EN UN SOLO QUERY*/
INSERT INTO Municipios (IdProvincia,Descripcion) VALUES 
(27,'CRISTÓBAL'),
(27,'DUVERGÉ'),
(27,'JIMANÍ'),
(27,'LA DESCUBIERTA'),
(27,'MELLA'),
(27,'POSTRER RÍO');

/*INSERCION DE LOS DATOS DE LA PROVINCIA PEDERNALES EN LA TABLA MUNICIPIOS TODOS EN UN SOLO QUERY*/
INSERT INTO Municipios (IdProvincia,Descripcion) VALUES 
(28,'OVIEDO'),
(28,'PEDERNALES');

/*INSERCION DE LOS DATOS DE LA PROVINCIA PERAVIA EN LA TABLA MUNICIPIOS TODOS EN UN SOLO QUERY*/
INSERT INTO Municipios (IdProvincia,Descripcion) VALUES 
(29,'BANÍ'),
(29,'NIZAO');

/*INSERCION DE LOS DATOS DE LA PROVINCIA SAN CRISTÓBAL EN LA TABLA MUNICIPIOS TODOS EN UN SOLO QUERY*/
INSERT INTO Municipios (IdProvincia,Descripcion) VALUES 
(30,'BAJOS DE HAINA'),
(30,'CAMBITA GARABITOS'),
(30,'LOS CACAOS'),
(30,'SABANA GRANDE DE PALENQUE'),
(30,'SAN CRISTÓBAL'),
(30,'SAN GREGORIO DE NIGUA'),
(30,'VILLA ALTAGRACIA'),
(30,'YAGUATE');

/*INSERCION DE LOS DATOS DE LA PROVINCIA SAN JOSÉ DE OCOA EN LA TABLA MUNICIPIOS TODOS EN UN SOLO QUERY*/
INSERT INTO Municipios (IdProvincia,Descripcion) VALUES 
(31,'RANCHO ARRIBA'),
(31,'SABANA LARGA'),
(31,'SAN JOSÉ DE OCOA');

/*INSERCION DE LOS DATOS DE LA PROVINCIA SAN JUAN EN LA TABLA MUNICIPIOS TODOS EN UN SOLO QUERY*/
INSERT INTO Municipios (IdProvincia,Descripcion) VALUES 
(32,'BOHECHÍO'),
(32,'EL CERCADO'),
(32,'JUAN DE HERRERA'),
(32,'LAS MATAS DE FARFÁN'),
(32,'SAN JUAN DE LA MAGUANA'),
(32,'VALLEJUELO');

/*INSERCION DE LOS DATOS DE LA PROVINCIA AZUA EN LA TABLA DISTRITOS MUNICIPALES TODOS EN UN SOLO QUERY*/
INSERT INTO Distritos_Municipales (IdMunicipio,Descripcion) VALUES 
(97,'BARRERAS'),
(97,'BARRO ARRIBA'),
(97,'CLAVELLINA'),
(97,'EMMA BALAGUER VIUDA VALLEJO'),
(97,'LAS BARÍAS-LA ESTANCIA'),
(97,'LAS LOMAS'),
(97,'LOS JOVILLOS'),
(97,'PUERTO VIEJO');

INSERT INTO Distritos_Municipales (IdMunicipio,Descripcion) VALUES 
(98,'ESTEBANÍA');

INSERT INTO Distritos_Municipales (IdMunicipio,Descripcion) VALUES 
(99,'GUAYABAL');

INSERT INTO Distritos_Municipales (IdMunicipio,Descripcion) VALUES 
(100,'HATILLO'),
(100,'PALMAR DE OCOA');

INSERT INTO Distritos_Municipales (IdMunicipio,Descripcion) VALUES 
(101,'VILLARPANDO'),
(101,'HATO NUEVO-CORTÉS');

INSERT INTO Distritos_Municipales (IdMunicipio,Descripcion) VALUES 
(102,'LA SIEMBRA'),
(102,'LAS LAGUNAS'),
(102,'LOS FRÍOS');

INSERT INTO Distritos_Municipales (IdMunicipio,Descripcion) VALUES 
(103,'PERALTA');

INSERT INTO Distritos_Municipales (IdMunicipio,Descripcion) VALUES 
(104,'EL ROSARIO');

INSERT INTO Distritos_Municipales (IdMunicipio,Descripcion) VALUES 
(105,'PROYECTO 4'),
(105,'GANADERO'),
(105,'PROYECTO 2-C');

INSERT INTO Distritos_Municipales (IdMunicipio,Descripcion) VALUES 
(106,'AMIAMA GÓMEZ'),
(106,'LOS TOROS'),
(106,'TÁBARA ABAJO');

/*INSERCION DE LOS DATOS DE LA PROVINCIA BAHORUCO EN LA TABLA DISTRITOS MUNICIPALES TODOS EN UN SOLO QUERY*/
INSERT INTO Distritos_Municipales (IdMunicipio,Descripcion) VALUES 
(109,'EL PALMAR');

INSERT INTO Distritos_Municipales (IdMunicipio,Descripcion) VALUES 
(107,'EL SALADO');

INSERT INTO Distritos_Municipales (IdMunicipio,Descripcion) VALUES 
(108,'LAS CLAVELLINAS');

INSERT INTO Distritos_Municipales (IdMunicipio,Descripcion) VALUES 
(110,'CABEZA DE TORO'),
(110,'MENA'),
(110,'MONSERRAT'),
(110,'SANTA BÁRBARA-EL 6'),
(110,'SANTANA'),
(110,'UVILLA');

INSERT INTO Distritos_Municipales (IdMunicipio,Descripcion) VALUES 
(111,'VILLA JARAGUA');

/*INSERCION DE LOS DATOS DE LA PROVINCIA BARAHONA EN LA TABLA DISTRITOS MUNICIPALES TODOS EN UN SOLO QUERY*/
INSERT INTO Distritos_Municipales (IdMunicipio,Descripcion) VALUES 
(112,'EL CACHÓN'),
(112,'LA GUÁZARA'),
(112,'VILLA CENTRAL');

INSERT INTO Distritos_Municipales (IdMunicipio,Descripcion) VALUES 
(113,'CABRAL');

INSERT INTO Distritos_Municipales (IdMunicipio,Descripcion) VALUES 
(114,'EL PEÑÓN');

INSERT INTO Distritos_Municipales (IdMunicipio,Descripcion) VALUES 
(115,'ARROYO DULCE');

INSERT INTO Distritos_Municipales (IdMunicipio,Descripcion) VALUES 
(116,'PESCADERÍA');

INSERT INTO Distritos_Municipales (IdMunicipio,Descripcion) VALUES 
(117,'PALO ALTO');

INSERT INTO Distritos_Municipales (IdMunicipio,Descripcion) VALUES 
(118,'BAHORUCO');

INSERT INTO Distritos_Municipales (IdMunicipio,Descripcion) VALUES 
(119,'LAS SALINAS');

INSERT INTO Distritos_Municipales (IdMunicipio,Descripcion) VALUES 
(120,'LOS PATOS');

INSERT INTO Distritos_Municipales (IdMunicipio,Descripcion) VALUES 
(121,'POLO');

INSERT INTO Distritos_Municipales (IdMunicipio,Descripcion) VALUES 
(122,'CANOA'),
(122,'FONDO NEGRO'),
(122,'QUITA CORAZA');

/*INSERCION DE LOS DATOS DE LA PROVINCIA DAJABÓN EN LA TABLA DISTRITOS MUNICIPALES TODOS EN UN SOLO QUERY*/
INSERT INTO Distritos_Municipales (IdMunicipio,Descripcion) VALUES 
(1,'CAÑONGO');

INSERT INTO Distritos_Municipales (IdMunicipio,Descripcion) VALUES 
(2,'MANUEL BUENO');

INSERT INTO Distritos_Municipales (IdMunicipio,Descripcion) VALUES 
(3,'CAPOTILLO'),
(3,'SANTIAGO DE LA CRUZ');

INSERT INTO Distritos_Municipales (IdMunicipio,Descripcion) VALUES 
(4,'PARTIDO');

INSERT INTO Distritos_Municipales (IdMunicipio,Descripcion) VALUES 
(5,'RESTAURACIÓN');

/*INSERCION DE LOS DATOS DE LA PROVINCIA DUARTE EN LA TABLA DISTRITOS MUNICIPALES TODOS EN UN SOLO QUERY*/
INSERT INTO Distritos_Municipales (IdMunicipio,Descripcion) VALUES 
(11,'CENOVÍ'),
(11,'JAYA'),
(11,'LA PEÑA'),
(11,'PRESIDENTE DON ANTONIO GUZMÁN FERNÁNDEZ');

INSERT INTO Distritos_Municipales (IdMunicipio,Descripcion) VALUES 
(6,'AGUACATE'),
(6,'LAS COLES');

INSERT INTO Distritos_Municipales (IdMunicipio,Descripcion) VALUES 
(7,'CASTILLO');

INSERT INTO Distritos_Municipales (IdMunicipio,Descripcion) VALUES 
(8,'SABANA GRANDE');

INSERT INTO Distritos_Municipales (IdMunicipio,Descripcion) VALUES 
(9,'LAS GUÁRANAS');

INSERT INTO Distritos_Municipales (IdMunicipio,Descripcion) VALUES 
(10,'PIMENTEL');

INSERT INTO Distritos_Municipales (IdMunicipio,Descripcion) VALUES 
(12,'AGUA SANTA DEL YUNA'),
(12,'BARRAQUITO'),
(12,'CRISTO REY DE GUARAGUAO'),
(12,'LAS TÁRANAS');

/*INSERCION DE LOS DATOS DE LA PROVINCIA EL SEIBO EN LA TABLA DISTRITOS MUNICIPALES TODOS EN UN SOLO QUERY*/
INSERT INTO Distritos_Municipales (IdMunicipio,Descripcion) VALUES 
(69,'PEDRO SÁNCHEZ'),
(69,'SAN FRANCISCO-VICENTILLO'),
(69,'SANTA LUCÍA');

INSERT INTO Distritos_Municipales (IdMunicipio,Descripcion) VALUES 
(70,'EL CEDRO'),
(70,'LA GINA');

/*INSERCION DE LOS DATOS DE LA PROVINCIA ELÍAS PIÑA EN LA TABLA DISTRITOS MUNICIPALES TODOS EN UN SOLO QUERY*/
INSERT INTO Distritos_Municipales (IdMunicipio,Descripcion) VALUES 
(124,'GUAYABO'),
(124,'SABANA LARGA');

INSERT INTO Distritos_Municipales (IdMunicipio,Descripcion) VALUES 
(123,'SABANA CRUZ'),
(123,'SABANA HIGÜERO');

INSERT INTO Distritos_Municipales (IdMunicipio,Descripcion) VALUES 
(125,'GUANITO');

INSERT INTO Distritos_Municipales (IdMunicipio,Descripcion) VALUES 
(126,'RANCHO DE LA GUARDIA');

INSERT INTO Distritos_Municipales (IdMunicipio,Descripcion) VALUES 
(127,'JUAN SANTIAGO');

INSERT INTO Distritos_Municipales (IdMunicipio,Descripcion) VALUES 
(128,'RÍO LIMPIO');

/*INSERCION DE LOS DATOS DE LA PROVINCIA ELÍAS PIÑA EN LA TABLA DISTRITOS MUNICIPALES TODOS EN UN SOLO QUERY*/
INSERT INTO Distritos_Municipales (IdMunicipio,Descripcion) VALUES 
(16,'CANCA LA REINA'),
(16,'EL HIGÜERITO'),
(16,'JOSÉ CONTRERAS'),
(16,'JUAN LÓPEZ'),
(16,'LA ORTEGA'),
(16,'LAS LAGUNAS'),
(16,'MONTE DE LA JAGUA'),
(16,'SAN VÍCTOR');

INSERT INTO Distritos_Municipales (IdMunicipio,Descripcion) VALUES 
(13,'CAYETANO GERMOSÉN');

INSERT INTO Distritos_Municipales (IdMunicipio,Descripcion) VALUES 
(14,'JOBA ARRIBA'),
(14,'VERAGUA'),
(14,'VILLA MAGANTE');

INSERT INTO Distritos_Municipales (IdMunicipio,Descripcion) VALUES 
(15,'JAMAO AL NORTE');

/*INSERCION DE LOS DATOS DE LA PROVINCIA HATO MAYOR EN LA TABLA DISTRITOS MUNICIPALES TODOS EN UN SOLO QUERY*/
INSERT INTO Distritos_Municipales (IdMunicipio,Descripcion) VALUES 
(72,'GUAYABO DULCE'),
(72,'MATA PALACIO'),
(72,'YERBA BUENA');

INSERT INTO Distritos_Municipales (IdMunicipio,Descripcion) VALUES 
(71,'EL VALLE');

INSERT INTO Distritos_Municipales (IdMunicipio,Descripcion) VALUES 
(73,'ELUPINA CORDERO DE LAS CAÑITAS');

/*INSERCION DE LOS DATOS DE LA PROVINCIA HERMANAS MIRABAL EN LA TABLA DISTRITOS MUNICIPALES TODOS EN UN SOLO QUERY*/
INSERT INTO Distritos_Municipales (IdMunicipio,Descripcion) VALUES 
(17,'JAMAO AFUERA');

INSERT INTO Distritos_Municipales (IdMunicipio,Descripcion) VALUES 
(18,'BLANCO');

INSERT INTO Distritos_Municipales (IdMunicipio,Descripcion) VALUES 
(19,'VILLA TAPIA');

/*INSERCION DE LOS DATOS DE LA PROVINCIA INDEPENDENCIA EN LA TABLA DISTRITOS MUNICIPALES TODOS EN UN SOLO QUERY*/
INSERT INTO Distritos_Municipales (IdMunicipio,Descripcion) VALUES 
(131,'BOCA DE CACHÓN'),
(131,'EL LIMÓN');

INSERT INTO Distritos_Municipales (IdMunicipio,Descripcion) VALUES 
(129,'BATEY 8');

INSERT INTO Distritos_Municipales (IdMunicipio,Descripcion) VALUES 
(130,'VENGAN A VER');

INSERT INTO Distritos_Municipales (IdMunicipio,Descripcion) VALUES 
(132,'LA DESCUBIERTA');

INSERT INTO Distritos_Municipales (IdMunicipio,Descripcion) VALUES 
(133,'LA COLONIA');

INSERT INTO Distritos_Municipales (IdMunicipio,Descripcion) VALUES 
(134,'GUAYABAL');

/*INSERCION DE LOS DATOS DE LA PROVINCIA LA ALTAGRACIA EN LA TABLA DISTRITOS MUNICIPALES TODOS EN UN SOLO QUERY*/
INSERT INTO Distritos_Municipales (IdMunicipio,Descripcion) VALUES 
(74,'LA OTRA BANDA'),
(74,'LAGUNAS DE NISIBÓN'),
(74,'VERÓN-PUNTA CANA');

INSERT INTO Distritos_Municipales (IdMunicipio,Descripcion) VALUES 
(75,'BAYAHIBE'),
(75,'BOCA DE YUMA');

/*INSERCION DE LOS DATOS DE LA PROVINCIA LA ROMANA EN LA TABLA DISTRITOS MUNICIPALES TODOS EN UN SOLO QUERY*/
INSERT INTO Distritos_Municipales (IdMunicipio,Descripcion) VALUES 
(77,'CALETA');

INSERT INTO Distritos_Municipales (IdMunicipio,Descripcion) VALUES 
(76,'GUAYMATE');

INSERT INTO Distritos_Municipales (IdMunicipio,Descripcion) VALUES 
(78,'CUMAYASA');

/*INSERCION DE LOS DATOS DE LA PROVINCIA LA VEGA EN LA TABLA DISTRITOS MUNICIPALES TODOS EN UN SOLO QUERY*/
INSERT INTO Distritos_Municipales (IdMunicipio,Descripcion) VALUES 
(23,'EL RANCHITO'),
(23,'RÍO VERDE ARRIBA');

INSERT INTO Distritos_Municipales (IdMunicipio,Descripcion) VALUES 
(20,'LA SABINA'),
(20,'TIREO');

INSERT INTO Distritos_Municipales (IdMunicipio,Descripcion) VALUES 
(21,'BUENA VISTA'),
(21,'MANABAO');

INSERT INTO Distritos_Municipales (IdMunicipio,Descripcion) VALUES 
(22,'RINCÓN');

/*INSERCION DE LOS DATOS DE LA PROVINCIA MARÍA TRINIDAD SÁNCHEZ EN LA TABLA DISTRITOS MUNICIPALES TODOS EN UN SOLO QUERY*/
INSERT INTO Distritos_Municipales (IdMunicipio,Descripcion) VALUES 
(26,'ARROYO AL MEDIO'),
(26,'LAS GORDAS'),
(26,'SAN JOSÉ DE MATANZAS');

INSERT INTO Distritos_Municipales (IdMunicipio,Descripcion) VALUES 
(24,'ARROYO SALADO'),
(24,'LA ENTRADA');

INSERT INTO Distritos_Municipales (IdMunicipio,Descripcion) VALUES 
(25,'EL POZO');

INSERT INTO Distritos_Municipales (IdMunicipio,Descripcion) VALUES 
(27,'RÍO SAN JUAN');

/*INSERCION DE LOS DATOS DE LA PROVINCIA MONSEÑOR NOUEL EN LA TABLA DISTRITOS MUNICIPALES TODOS EN UN SOLO QUERY*/
INSERT INTO Distritos_Municipales (IdMunicipio,Descripcion) VALUES 
(28,'ARROYO TORO-MASIPEDRO'),
(28,'LA SALVIA-LOS QUEMADOS'),
(28,'JAYACO'),
(28,'JUMA BEJUCAL'),
(28,'SABANA DEL PUERTO');

INSERT INTO Distritos_Municipales (IdMunicipio,Descripcion) VALUES 
(29,'MAIMÓN');

INSERT INTO Distritos_Municipales (IdMunicipio,Descripcion) VALUES 
(30,'JUAN ADRIÁN'),
(30,'VILLA SONADOR');

/*INSERCION DE LOS DATOS DE LA PROVINCIA MONTE CRISTI EN LA TABLA DISTRITOS MUNICIPALES TODOS EN UN SOLO QUERY*/
INSERT INTO Distritos_Municipales (IdMunicipio,Descripcion) VALUES 
(34,'MONTE CRISTI');

INSERT INTO Distritos_Municipales (IdMunicipio,Descripcion) VALUES 
(31,'PALO VERDE');

INSERT INTO Distritos_Municipales (IdMunicipio,Descripcion) VALUES 
(32,'CANA CHAPETÓN'),
(32,'HATILLO PALMA'),
(32,'VILLA ELISA');

INSERT INTO Distritos_Municipales (IdMunicipio,Descripcion) VALUES 
(33,'LAS MATAS DE SANTA CRUZ');

INSERT INTO Distritos_Municipales (IdMunicipio,Descripcion) VALUES 
(35,'PEPILLO SALCEDO');

INSERT INTO Distritos_Municipales (IdMunicipio,Descripcion) VALUES 
(36,'VILLA VÁSQUEZ');

/*INSERCION DE LOS DATOS DE LA PROVINCIA MONTE PLATA EN LA TABLA DISTRITOS MUNICIPALES TODOS EN UN SOLO QUERY*/
INSERT INTO Distritos_Municipales (IdMunicipio,Descripcion) VALUES 
(80,'BOYÁ'),
(80,'CHIRINO'),
(80,'DON JUAN');

INSERT INTO Distritos_Municipales (IdMunicipio,Descripcion) VALUES 
(79,'BAYAGUANA');

INSERT INTO Distritos_Municipales (IdMunicipio,Descripcion) VALUES 
(81,'PERALVILLO');

INSERT INTO Distritos_Municipales (IdMunicipio,Descripcion) VALUES 
(82,'GONZALO'),
(82,'MAJAGUAL');

INSERT INTO Distritos_Municipales (IdMunicipio,Descripcion) VALUES 
(83,'LOS BOTADOS');

/*INSERCION DE LOS DATOS DE LA PROVINCIA PEDERNALES EN LA TABLA DISTRITOS MUNICIPALES TODOS EN UN SOLO QUERY*/
INSERT INTO Distritos_Municipales (IdMunicipio,Descripcion) VALUES 
(136,'JOSÉ FRANCISCO PEÑA GÓMEZ'),
(136,'JUANCHO');

INSERT INTO Distritos_Municipales (IdMunicipio,Descripcion) VALUES 
(135,'OVIEDO');

/*INSERCION DE LOS DATOS DE LA PROVINCIA PERAVIA EN LA TABLA DISTRITOS MUNICIPALES TODOS EN UN SOLO QUERY*/
INSERT INTO Distritos_Municipales (IdMunicipio,Descripcion) VALUES 
(137,'CATALINA'),
(137,'EL CARRETÓN'),
(137,'EL LIMONAL'),
(137,'LAS BARÍAS'),
(137,'MATANZAS'),
(137,'PAYA'),
(137,'SABANA BUEY'),
(137,'VILLA FUNDACIÓN'),
(137,'VILLA SOMBRERO');

INSERT INTO Distritos_Municipales (IdMunicipio,Descripcion) VALUES 
(138,'PIZARRETE'),
(138,'SANTANA');

/*INSERCION DE LOS DATOS DE LA PROVINCIA PUERTO PLATA EN LA TABLA DISTRITOS MUNICIPALES TODOS EN UN SOLO QUERY*/
INSERT INTO Distritos_Municipales (IdMunicipio,Descripcion) VALUES 
(42,'MAIMÓN'),
(42,'YÁSICA ARRIBA');

INSERT INTO Distritos_Municipales (IdMunicipio,Descripcion) VALUES 
(37,'RÍO GRANDE');

INSERT INTO Distritos_Municipales (IdMunicipio,Descripcion) VALUES 
(38,'GUANANICO');

INSERT INTO Distritos_Municipales (IdMunicipio,Descripcion) VALUES 
(39,'IMBERT');

INSERT INTO Distritos_Municipales (IdMunicipio,Descripcion) VALUES 
(40,'NAVAS');

INSERT INTO Distritos_Municipales (IdMunicipio,Descripcion) VALUES 
(41,'BELLOSO'),
(41,'ESTRECHO'),
(41,'LA ISABELA');

INSERT INTO Distritos_Municipales (IdMunicipio,Descripcion) VALUES 
(43,'CABARETE'),
(43,'SABANETA DE YÁSICA');

INSERT INTO Distritos_Municipales (IdMunicipio,Descripcion) VALUES 
(44,'ESTERO HONDO'),
(44,'GUALETE'),
(44,'LA JAIBA');

INSERT INTO Distritos_Municipales (IdMunicipio,Descripcion) VALUES 
(45,'VILLA MONTELLANO');

/*INSERCION DE LOS DATOS DE LA PROVINCIA SAMANÁ EN LA TABLA DISTRITOS MUNICIPALES TODOS EN UN SOLO QUERY*/
INSERT INTO Distritos_Municipales (IdMunicipio,Descripcion) VALUES 
(47,'ARROYO BARRIL'),
(47,'EL LIMÓN'),
(47,'LAS GALERAS');

INSERT INTO Distritos_Municipales (IdMunicipio,Descripcion) VALUES 
(46,'LAS TERRENAS');

INSERT INTO Distritos_Municipales (IdMunicipio,Descripcion) VALUES 
(48,'SÁNCHEZ');

/*INSERCION DE LOS DATOS DE LA PROVINCIA SAN CRISTÓBAL EN LA TABLA DISTRITOS MUNICIPALES TODOS EN UN SOLO QUERY*/
INSERT INTO Distritos_Municipales (IdMunicipio,Descripcion) VALUES 
(143,'HATO DAMAS');

INSERT INTO Distritos_Municipales (IdMunicipio,Descripcion) VALUES 
(139,'EL CARRIL');

INSERT INTO Distritos_Municipales (IdMunicipio,Descripcion) VALUES 
(140,'CAMBITA EL PUEBLECITO');

INSERT INTO Distritos_Municipales (IdMunicipio,Descripcion) VALUES 
(141,'LOS CACAOS');

INSERT INTO Distritos_Municipales (IdMunicipio,Descripcion) VALUES 
(142,'SABANA GRANDE DE PALENQUE');

INSERT INTO Distritos_Municipales (IdMunicipio,Descripcion) VALUES 
(144,'SAN GREGORIO DE NIGUA');

INSERT INTO Distritos_Municipales (IdMunicipio,Descripcion) VALUES 
(145,'LA CUCHILLA'),
(145,'MEDINA'),
(145,'SAN JOSÉ DEL PUERTO');

INSERT INTO Distritos_Municipales (IdMunicipio,Descripcion) VALUES 
(146,'YAGUATE');

/*INSERCION DE LOS DATOS DE LA PROVINCIA SAN JOSÉ DE OCOA EN LA TABLA DISTRITOS MUNICIPALES TODOS EN UN SOLO QUERY*/
INSERT INTO Distritos_Municipales (IdMunicipio,Descripcion) VALUES 
(149,'EL NARANJAL'),
(149,'EL PINAR'),
(149,'LA CIÉNAGA'),
(149,'NIZAO-LAS AUYAMAS');

INSERT INTO Distritos_Municipales (IdMunicipio,Descripcion) VALUES 
(147,'RANCHO ARRIBA');

INSERT INTO Distritos_Municipales (IdMunicipio,Descripcion) VALUES 
(148,'SABANA LARGA');

/*INSERCION DE LOS DATOS DE LA PROVINCIA SAN JUAN EN LA TABLA DISTRITOS MUNICIPALES TODOS EN UN SOLO QUERY*/
INSERT INTO Distritos_Municipales (IdMunicipio,Descripcion) VALUES 
(154,'EL ROSARIO'),
(154,'GUANITO'),
(154,'HATO DEL PADRE'),
(154,'HATO NUEVO'),
(154,'LA JAGUA'),
(154,'LAS CHARCAS DE MARÍA NOVA'),
(154,'PEDRO CORTO'),
(154,'SABANA ALTA'),
(154,'SABANETA');

INSERT INTO Distritos_Municipales (IdMunicipio,Descripcion) VALUES 
(150,'ARROYO CANO'),
(150,'YAQUE');

INSERT INTO Distritos_Municipales (IdMunicipio,Descripcion) VALUES 
(151,'BATISTA'),
(151,'DERRUMBADERO');

INSERT INTO Distritos_Municipales (IdMunicipio,Descripcion) VALUES 
(152,'JÍNOVA');

INSERT INTO Distritos_Municipales (IdMunicipio,Descripcion) VALUES 
(153,'CARRERA DE YEGUA'),
(153,'MATAYAYA');

INSERT INTO Distritos_Municipales (IdMunicipio,Descripcion) VALUES 
(155,'JORJILLO');

/*INSERCION DE LOS DATOS DE LA PROVINCIA SAN PEDRO DE MACORÍS EN LA TABLA DISTRITOS MUNICIPALES TODOS EN UN SOLO QUERY*/
INSERT INTO Distritos_Municipales (IdMunicipio,Descripcion) VALUES 
(89,'SAN PEDRO DE MACORÍS');

INSERT INTO Distritos_Municipales (IdMunicipio,Descripcion) VALUES 
(84,'CONSUELO');

INSERT INTO Distritos_Municipales (IdMunicipio,Descripcion) VALUES 
(85,'GUAYACANES');

INSERT INTO Distritos_Municipales (IdMunicipio,Descripcion) VALUES 
(86,'QUISQUEYA');

INSERT INTO Distritos_Municipales (IdMunicipio,Descripcion) VALUES 
(87,'RAMÓN SANTANA');

INSERT INTO Distritos_Municipales (IdMunicipio,Descripcion) VALUES 
(88,'EL PUERTO'),
(88,'GAUTIER');

/*INSERCION DE LOS DATOS DE LA PROVINCIA SÁNCHEZ RAMÍREZ EN LA TABLA DISTRITOS MUNICIPALES TODOS EN UN SOLO QUERY*/
INSERT INTO Distritos_Municipales (IdMunicipio,Descripcion) VALUES 
(50,'CABALLERO'),
(50,'COMEDERO ARRIBA'),
(50,'QUITA SUEÑO');

INSERT INTO Distritos_Municipales (IdMunicipio,Descripcion) VALUES 
(49,'LA CUEVA'),
(49,'PLATANAL');

INSERT INTO Distritos_Municipales (IdMunicipio,Descripcion) VALUES 
(51,'FANTINO');

INSERT INTO Distritos_Municipales (IdMunicipio,Descripcion) VALUES 
(52,'ANGELINA'),
(52,'LA BIJA'),
(52,'HERNANDO ALONZO');

/*INSERCION DE LOS DATOS DE LA PROVINCIA SANTIAGO EN LA TABLA DISTRITOS MUNICIPALES TODOS EN UN SOLO QUERY*/
INSERT INTO Distritos_Municipales (IdMunicipio,Descripcion) VALUES 
(59,'BAITOA'),
(59,'HATO DEL YAQUE'),
(59,'LA CANELA'),
(59,'PEDRO GARCÍA'),
(59,'SAN FRANCISCO DE JACAGUA');

INSERT INTO Distritos_Municipales (IdMunicipio,Descripcion) VALUES 
(53,'BISONÓ');

INSERT INTO Distritos_Municipales (IdMunicipio,Descripcion) VALUES 
(54,'EL CAIMITO'),
(54,'JUNCALITO');

INSERT INTO Distritos_Municipales (IdMunicipio,Descripcion) VALUES 
(55,'LAS PALOMAS');

INSERT INTO Distritos_Municipales (IdMunicipio,Descripcion) VALUES 
(56,'CANABACOA'),
(56,'GUAYABAL');

INSERT INTO Distritos_Municipales (IdMunicipio,Descripcion) VALUES 
(57,'SABANA IGLESIA');

INSERT INTO Distritos_Municipales (IdMunicipio,Descripcion) VALUES 
(58,'EL RUBIO'),
(58,'LA CUESTA'),
(58,'LAS PLACETAS');

INSERT INTO Distritos_Municipales (IdMunicipio,Descripcion) VALUES 
(60,'CANCA LA PIEDRA');

INSERT INTO Distritos_Municipales (IdMunicipio,Descripcion) VALUES 
(61,'EL LIMÓN'),
(61,'PALMAR ARRIBA');

/*INSERCION DE LOS DATOS DE LA PROVINCIA SANTIAGO RODRÍGUEZ EN LA TABLA DISTRITOS MUNICIPALES TODOS EN UN SOLO QUERY*/
INSERT INTO Distritos_Municipales (IdMunicipio,Descripcion) VALUES 
(63,'SAN IGNACIO DE SABANETA');

INSERT INTO Distritos_Municipales (IdMunicipio,Descripcion) VALUES 
(64,'LOS ALMÁCIGOS');

INSERT INTO Distritos_Municipales (IdMunicipio,Descripcion) VALUES 
(62,'MONCIÓN');

/*INSERCION DE LOS DATOS DE LA PROVINCIA SANTO DOMINGO EN LA TABLA DISTRITOS MUNICIPALES TODOS EN UN SOLO QUERY*/
INSERT INTO Distritos_Municipales (IdMunicipio,Descripcion) VALUES 
(94,'SAN LUIS');

INSERT INTO Distritos_Municipales (IdMunicipio,Descripcion) VALUES 
(90,'LA CALETA');

INSERT INTO Distritos_Municipales (IdMunicipio,Descripcion) VALUES 
(91,'PALMAREJO-VILLA LINDA'),
(91,'PANTOJA');

INSERT INTO Distritos_Municipales (IdMunicipio,Descripcion) VALUES 
(92,'LA CUABA'),
(92,'LA GUÁYIGA');

INSERT INTO Distritos_Municipales (IdMunicipio,Descripcion) VALUES 
(93,'HATO VIEJO');

INSERT INTO Distritos_Municipales (IdMunicipio,Descripcion) VALUES 
(95,' LA VICTORIA');

INSERT INTO Distritos_Municipales (IdMunicipio,Descripcion) VALUES 
(96,'SANTO DOMINGO OESTE');

/*INSERCION DE LOS DATOS DE LA PROVINCIA VALVERDE EN LA TABLA DISTRITOS MUNICIPALES TODOS EN UN SOLO QUERY*/
INSERT INTO Distritos_Municipales (IdMunicipio,Descripcion) VALUES 
(67,'ÁMINA'),
(67,'GUATAPANAL'),
(67,'JAIBÓN (PUEBLO NUEVO)');

INSERT INTO Distritos_Municipales (IdMunicipio,Descripcion) VALUES 
(65,'BOCA DE MAO'),
(65,'JICOMÉ'),
(65,'MAIZAL'),
(65,'PARADERO');

INSERT INTO Distritos_Municipales (IdMunicipio,Descripcion) VALUES 
(66,'CRUCE DE GUAYACANES'),
(66,'JAIBÓN'),
(66,'LA CAYA');

/*INSERCION DE LOS DATOS EN LA TABLA CLIENTES TODOS EN UN SOLO QUERY*/
INSERT INTO Empleados (Nombre,Apellido,Cedula,Fecha_Nacimiento,Genero,IdRegion,IdProvincia,IdMunicipio,IdDistritoMunicipal,IdEmpleadoSupervisor) 
VALUES
('LUIS ALBERTO','CALDERON DURAN','40236872830','1999-04-21','M',1,3,16,89,NULL),
('DOMINGO ANTONIO','ESTRELLA PEÑA','40242133326','1996-12-16','M',1,7,29,139,1),
('ROBERTO','DE LA ROSA','04600038188','1952-08-12','M',1,9,42,172,1),
('JULIO','CESAR POLANCO','03100849318','1958-05-07','M',1,10,47,188,2),
('JUAN SANTIAGO','CORDERO NUÑEZ','00109459529','1947-05-23','M',1,12,56,251,2),
('GUILLERMO YSRAEL','MATOS LUGO','01000080802','1966-09-21','M',1,12,61,257,3),
('FREDY LEIDY','CASTILLO NUÑEZ','40231069754','2000-11-20','F',3,23,99,10,3),
('FRANCISCO JAVIER','RODRIGUEZ CAMACHO','02601276609','1989-04-04','M',3,23,102,16,4),
('ANGEL VALERIO','MORDAN','00200838928','1965-02-11','M',3,23,104,19,4),
('DANY','SANTANA','02500482910','1989-02-09','M',3,24,110,33,4),
('ELISEO DARIO ESTEBAN','MARTINEZ AQUINO','00116902479','1983-12-30','M',3,26,124,77,5),
('MARTIRES DE JESUS','GOMEZ ALCANTARA','07300181422','1989-12-07','M',3,26,125,80,5),
('VICTOR RAFAEL','PEÑA SOSA','40225719828','1995-12-08','M',3,27,131,106,5),
('JUAN JOSE','GONELL GARCIA','40225959374','1995-07-05','M',3,27,134,111,6),
('ERIBERTO','TORRES RODRIGUEZ','03400536151','1986-05-15','M',3,29,138,171,6),
('JULIO ARTURO','MEJIA','03400503276','1984-07-01','M',3,31,148,207,6),
('JULIO ANDRES','GARCIA CASTILLO','09700037972','1949-09-23','M',3,32,154,208,7),
('ALTAGRACIA','MUÑOZ ALMONTE','40220250498','1990-07-28','F',3,32,154,209,7),
('JENNEDY CRISTINA','MINAYA DUARTE','40227580244','1997-03-19','F',2,22,96,270,7),
('JUAN LUIS','FLORES PEÑA','40212181263','1997-03-12','M',3,30,141,195,19),
('DAVID','RODRIGUEZ GARCIA','02600341230','1972-03-23','M',3,29,137,168,20);

INSERT INTO Tipo_Telefonos (TipoTelefono) VALUES ('MOVIL'),('HOGAR'),('TRABAJO');

INSERT INTO Telefonos (IdEmpleado,Telefono,IdTipoTelefono) VALUES (1,'8094754444',1);
INSERT INTO Telefonos (IdEmpleado,Telefono,IdTipoTelefono) VALUES (2,'8297557988',1),(2,'8097228514',2);
INSERT INTO Telefonos (IdEmpleado,Telefono,IdTipoTelefono) VALUES (3,'8294202777',1),(3,'8297618205',2),(3,'8296550029',3);
INSERT INTO Telefonos (IdEmpleado,Telefono,IdTipoTelefono) VALUES (4,'8297618206',1);
INSERT INTO Telefonos (IdEmpleado,Telefono,IdTipoTelefono) VALUES (5,'8297608024',1),(5,'8297618215',2);
INSERT INTO Telefonos (IdEmpleado,Telefono,IdTipoTelefono) VALUES (6,'8292228422',1),(6,'8297618213',2),(6,'8097228809',3);
INSERT INTO Telefonos (IdEmpleado,Telefono,IdTipoTelefono) VALUES (7,'8297617021',1);
INSERT INTO Telefonos (IdEmpleado,Telefono,IdTipoTelefono) VALUES (8,'8297617022',1),(8,'8297450087',2);
INSERT INTO Telefonos (IdEmpleado,Telefono,IdTipoTelefono) VALUES (9,'8297618223',1),(9,'8494523552',2),(9,'8297618217',3);
INSERT INTO Telefonos (IdEmpleado,Telefono,IdTipoTelefono) VALUES (10,'8297618216',1);
INSERT INTO Telefonos (IdEmpleado,Telefono,IdTipoTelefono) VALUES (11,'8297608025',1),(11,'8297557988',2);
INSERT INTO Telefonos (IdEmpleado,Telefono,IdTipoTelefono) VALUES (12,'8292228439',1),(12,'8297618264',2),(12,'8297618209',3);
INSERT INTO Telefonos (IdEmpleado,Telefono,IdTipoTelefono) VALUES (13,'8297618211',1);
INSERT INTO Telefonos (IdEmpleado,Telefono,IdTipoTelefono) VALUES (14,'8097615148',1),(14,'8297617025',2);
INSERT INTO Telefonos (IdEmpleado,Telefono,IdTipoTelefono) VALUES (15,'8294201081',1),(15,'8297618207',2),(15,'8294200872',3);
INSERT INTO Telefonos (IdEmpleado,Telefono,IdTipoTelefono) VALUES (16,'8294201080',1);
INSERT INTO Telefonos (IdEmpleado,Telefono,IdTipoTelefono) VALUES (17,'8297618222',1),(17,'8097228845',2);
INSERT INTO Telefonos (IdEmpleado,Telefono,IdTipoTelefono) VALUES (18,'8297602400',1),(18,'8293447223',2),(18,'8294201554',3);
INSERT INTO Telefonos (IdEmpleado,Telefono,IdTipoTelefono) VALUES (19,'8494522544',1);
INSERT INTO Telefonos (IdEmpleado,Telefono,IdTipoTelefono) VALUES (20,'8297618214',1),(20,'8494524220',2);
INSERT INTO Telefonos (IdEmpleado,Telefono,IdTipoTelefono) VALUES (21,'8297618218',1),(21,'8297557987',2),(21,'8297618210',3);






